name: event_bus
version: 2.1.0
description: A simple Event Bus using Dart Streams for decoupling applications
repository: https://github.com/marcojakob/dart-event-bus
homepage: https://code.makery.ch/library/dart-event-bus/
environment:
  sdk: '>=2.19.6 <4.0.0'
dev_dependencies:
  build_runner: '>=2.4.7 <3.0.0'
  build_web_compilers: '>=4.0.0 <5.0.0'
  build_test: '>=2.0.0 <3.0.0'
  logging: '>=1.0.0 <2.0.0'
  test: '>=1.5.0 <2.0.0'
